Revert "helpers: check_for_legacy_containers on starting infra"
This reverts commit 92c831711c4aabb0d2d18eae8df17e4a9a659385.
This causes failures on local system in case previous test is aborted in
the middle and automation proxy container is not shut down.

error log:
           Exception: Found containers with different prefixes: ['automation_proxy', 'docker-compose_collate-service_1', 'docker-compose_seaweedfs-s3_1', 'docker-compose_permission-management-service_1', 'docker-compose_seaweedfs-filer_1', 'docker-compose_seaweedfs-volume_1', 'docker-compose_consul-agent_1', 'docker-compose_seaweedfs-master_1', 'docker-compose_logrotate_1', 'docker-compose_memsql_1', 'docker-compose_zookeeper_1', 'docker-compose_postgres_1', 'docker-compose_consul_1', 'docker-compose_nginx_1', 'docker-compose_rtstreamer_1', 'docker-compose_docker-hoster_1', 'docker-compose_redis_1', 'docker-compose_kafka-hq_1', 'docker-compose_regions-service_1']. Please prune accordingly and rerun test.