lab: remove usage of asyncmock.
recent mock package  4.0.0 does not support asyncmock anymore. Here is
the exception:
>>> import asyncmock
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/florent/venv_mock_issue/lib/python3.7/site-packages/asyncmock/__init__.py", line 29, in <module>
    class AsyncCallableMixin(CallableMixin):
NameError: name 'CallableMixin' is not defined

Issue link: https://github.com/timsavage/asyncmock/issues/4
moreover latest mock package already contains its own asyncmock that we
can use, hence we will just use what comes with mock package