tunnel.py: catch OSError
The following error is thrown when connection is reset, which just garbages up
the logs and doesnt need any handling:
Traceback (most recent call last):
  File "/home/user/synced_core_repos/automation-infra/infra/model/tunnel.py", line 113, in handle
    data = self.request.recv(1024)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/synced_core_repos/automation-infra/infra/model/tunnel.py", line 100, in handle
    self.request.getpeername(),
OSError: [Errno 107] Transport endpoint is not connected